name: Build and deploy
 
on:
  push:
    branches:
      - 'ci_setup'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: temurin

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

    
      - name: Prepare Gradle environment
        run: |
 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      
      - name: Build release apk
        run: ./gradlew assembleRelease
        
      - name: Upload release apk
        uses: actions/upload-artifact@v4
        with:
          name: mastodon-release.apk
          path: build/outputs/apk/release/mastodon-release.apk
      - name: Build githubRelease apk
        run: ./gradlew assembleGithubRelease
        
      - name: Upload githubRelease apk
        uses: actions/upload-artifact@v4
        with:
          name: mastodon-githubRelease.apk
          path: build/outputs/apk/githubRelease/mastodon-githubRelease.apk

      - name: Upload mappings
        uses: actions/upload-artifact@v4
        with:
          name: mappings
          path: build/outputs/mapping/*/mapping.txt
