
name: Build and deploy
 
on:
  push:
    branches:
      - 'ci_setup'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: temurin

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Decode keystore
        uses: timheuer/base64-to-file@v1
        id: android_keystore
        with:
          fileName: "release.jks"
          encodedString: ${{ secrets.KEYSTORE_FILE }}

      - name: Prepare Gradle environment
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
       #- name: Build and deploy to Google Play
       #  run: bundle exec fastlane deploy
       #  env:
       #   KEYSTORE_FILE: ${{ steps.android_keystore.outputs.filePath }}
       #   KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
       #   SUPPLY_JSON_KEY_DATA: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
       #   SUPPLY_SKIP_UPLOAD_METADATA: true
       #   SUPPLY_SKIP_UPLOAD_CHANGELOGS: true

      - name: Build debug apk
        run: ./gradlew assembleDebug
       # env:
        #  KEYSTORE_FILE: ${{ steps.android_keystore.outputs.filePath }}
        #  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Upload debug apk
        uses: actions/upload-artifact@v4
        with:
          name: mastodon-debug.apk
          path: mastodon/build/outputs/apk/debug/mastodon-debug.apk

# Send to the APK to Telegram
      - name: Send the APK to Telegram
        env:
          APK_PATH: mastodon/build/outputs/apk/debug/mastodon-debug.apk
          BOT_API_KEY: ${{ secrets.BOT_API_KEY }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          curl -F chat_id=$CHAT_ID -F document=@"${APK_PATH}" -F caption="Template-$(date +"%Y%m%d-%H%M")" https://api.telegram.org/bot${BOT_API_KEY}/sendDocument
